name: Katalon Test and Code Scanning

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '8.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey=${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'

  code-scanning:
    needs: katalon-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy
          echo "Groovy installed successfully"

      - name: Install Dependencies
        run: |
          echo "Configuring Grape..."
          mkdir -p ~/.groovy
          echo "groovy.grape.report.downloads=true" > ~/.groovy/grapeConfig.xml
          echo "Configured Grape"
          groovy -e "groovy.grape.Grape.grab(group:'commons-cli', module:'commons-cli', version:'1.4')"
          echo "Dependencies installed"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Create and Upload ZIP
        run: |
          # Create a ZIP file from the CodeQL database
          zip -r codeql_databases/javascript.zip /home/runner/work/_temp/codeql_databases

          # Upload the ZIP file as an artifact
          mv codeql_databases/javascript.zip $GITHUB_WORKSPACE/javascript.zip
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      
      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: codeql-database
          path: $GITHUB_WORKSPACE/javascript.zip
