name: Katalon Code Scan with Codacy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      
jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy
        working-directory: ${{ github.workspace }}

      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '8.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey=${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
